### ISSUE TITLE
can we make 404 page interesting/useful?

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#127]
this is what we get now : http://www.nepalmap.org/profiles/nepal

**Comment by studenton** [comment]
Here's the reason.

```
You're seeing this error because you have DEBUG = True in your Django settings file.
Change that to False, and Django will display a standard 404 page.
```

But, when I set DEBUG = False in local instance, the site breaks. The links for static resources like CSS, JS no longer work.  

I read upon the issue and this [stackoverflow thread](http://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail) discusses on it. It says the site will work in production with DEBUG = False. 

@cliftonmcintosh ?

**Comment by cliftonmcintosh** [comment]
I will take a look and see what I can learn. Wazimap Kenya has their site set up so that it displays a better view. See here, for example: https://kenya.wazimap.org/profiles/country-NP-nepal/

**Comment by studenton** [comment]
We also get the same 404 page when debug is set to False.

![screenshot from 2017-01-12 18 43 13](https://cloud.githubusercontent.com/assets/8587189/21890712/12f60ebc-d8f7-11e6-8b27-f769a5fe415f.png)

The thing is CSS and JS are breaking locally. Internet forums say that it'll work on production server. 

There is a mention of ALLOWED_HOSTS on [Deployment checklist](https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/) on Official Django Documentation.

**Comment by prashishh** [comment]
@studenton - Hmmm.. wonder why it is not working locally.

**Comment by cliftonmcintosh** [comment]
With our setup on the servers, it turns out to be easy to make this change.

We have to set `DEBUG = True` but we don't have to worry about the `ALLOWED_HOSTS`, and it seems that is because we are using a Unix socket with nginx and gunicorn.

I am planning on merging the dev branch into master and using master on www.nepalmap.org. When I do, I will set `DEBUG = True` on the master branch and then we will have a better 404 on www.nepalmap.org.

For now, I have set it manually. Here is a screenshot:

![better-404](https://cloud.githubusercontent.com/assets/3824492/21915623/be79d24c-d900-11e6-88fb-90c7a935b647.png)

**Comment by cliftonmcintosh** [comment]
I've done the following:

1. Merged dev into master
2. Updated master to use `DEBUG = False`
3. Set www.nepalmap.org to use master

**Comment by prashishh** [comment]
Thank you @cliftonmcintosh.
