### ISSUE TITLE
Add 2017 flood data

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#186]
District level data for flood damage in the 2017 floods.

http://codefornepal.org/en/2017/08/nepalflood/

Statistics here: https://docs.google.com/spreadsheets/d/1MuTWPtD67VO1kbMCEpyPvlnuPsdVFHFZ1wjj7KKRyAo/edit#gid=1841636268

These are the statistics most amenable to presentation in NepalMap:
- total deaths
- damaged homes

See @ravinepal's comment below about updated data and data choices.

District-level data is on the district-level sheet.

Districts that are not listed on the sheet should be given counts of zero for each statistic.

@ravinepal do we have a list of all 75 districts in Nepal that can be used as an easy reference for a contributor who might want to take on this issue?

**Comment by ravinepal** [comment]
Here's the updated flood, landslides data from 2010--08-08 to 2017-08-30 - https://docs.google.com/spreadsheets/d/1WGEsVT0eiWnE34uA9-z3a4cKStcYhCvo_3ANiVzZTYk/edit?ts=59c8020a#gid=617759520 

I believe we should only visualize column B (Total (Flood+Heavy rainfall + Landslide))

**Comment by crispg72** [comment]
Looking at this now.

Would this be done as a SimpleTable, similar to [polling places](https://github.com/Code4Nepal/nepalmap_app/blob/dev/sql/simpletables/pollingplaces.sql) for example since only one column is being visualized? This would mean just one value on the profile page.

I notice in the latest document there are values in column B for all districts.

**Comment by cliftonmcintosh** [comment]
@crispg72

Yes, a SimpleTable fits for this, and I believe you are right that the beer data set has a total number of deaths for each district
