### ISSUE TITLE
Workflow for branches and deployment

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#38]
@prashishh 

Would you have a few minutes to describe the workflow that you think is best for merging work into the different branches and deploying the `test` and `master` branches? I'm particularly curious about how and when work goes from the `dev` branch into `test` and when those changes get deployed to an environment.
- What is the strategy for merging `dev` into `test`?
- Will merges be on a schedule of some sort?
- Will there be tests or some other measure that must be passed before merges into `test` occur?
- Is it possible that we need only two branches, `test` and `master`?

Would this information be something to go into a README file or on the wiki?

**Comment by prashishh** [comment]
I totally missed this. Sorry for the late response.

Here is what I think, please let me know your thought on the strategy described below.
1) & 2) - We can plan out releases - release, basically would mean the `dev` branch merging to `test` branch and eventually moving up the chain - `stage`, `master`. I would exclude staging in our case because of our limited resources. We can roll our releases every 2/3 weeks depending on the number of features/bug fixes going to that release. I usually follow [this guide](http://semver.org/) to number the major, minor and patch version. 

Once we merge `dev` to `test`, we can freeze the merge until the next release (we can be flexible sometimes depending on the situation). But, it is a good strategy to follow so that we know what all features are going out in each release. After the release, we can update the Change log [here](https://github.com/Code4Nepal/nepalmap_app/releases) and add it to the README.

3) I'm a big fan of Continous Integration but I'm not aware of how CI can be integrated for Wazipmap. Travis CI or Jenkins are the biggest players that I know of. I'm inclined towards Travis CI though. Thoughts? @cliftonmcintosh @studenton 

4) Answer above ^^. Just two branches should be okay for this project.

5) Should totally write our decided workflow in the wiki.
