### ISSUE TITLE
Change bar chart colors to fit Code for Nepal color scheme

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#44]
The current bar charts are green and orange. Are there other options that might match the Code for Nepal color scheme better?

Here is a sample of the current color scheme:
![green-orange-bar-charts](https://cloud.githubusercontent.com/assets/3824492/19213387/220f411e-8d31-11e6-86ee-d40c0376e233.png)

**Comment by studenton** [comment]
@cliftonmcintosh C4N colors schemes are red and blue. I'll see where the styles for graphs are. Thanks for pointing out.

**Comment by prashishh** [comment]
+1

**Comment by prashishh** [comment]
@ravinepal - good point.
@studenton - thanks for getting on this.

FYI - Instead of MVP label, we can use MVP as our Milestone. That way, we can see all the issues related to the Milestone and burn down rate in the 'Burndown' section.

<img width="1012" alt="screen shot 2016-10-17 at 11 06 36 pm" src="https://cloud.githubusercontent.com/assets/966151/19466240/724af436-94be-11e6-80b5-496d433a1bba.png">
