### ISSUE TITLE
Pretty URI (for districts)

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#66]
URI of districts have district number in them - http://nepalmap.org/profiles/district-19-sindhuli/

Is it possible to show only the district name?

**Comment by cliftonmcintosh** [comment]
Current functionality is default for wazimap. It just happens.

http://i.imgur.com/YsbKHg1.gif

**Comment by cliftonmcintosh** [comment]
@prashishh 

The URIs are designed this way so that Wazimap knows which geography it needs to get data for. See [here](https://github.com/Code4SA/wazimap/blob/master/wazimap/urls.py#L40). Uniqueness of a geography is based on a combination of the level (such as "district") and the identifier at that level (such as "74"). Wazimap uses those parts of the URL to make the right database calls.

**Comment by prashishh** [comment]
@cliftonmcintosh - Oh, I see. Thanks for the explanation. Appreciate it.

**Comment by ravinepal** [comment]
Thanks for the clairfication, Cliff!
