### ISSUE TITLE
Breakdown by city within a district.

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#68]
More of a research task.

Would be amazing!

**Comment by ravinepal** [comment]
We need shape files for those, @prashishh. Is there a way to extract from http://www.openstreetmap.org/ 

We are also looking for shape files of VDCs. Can you spread the word among the mappers community to see if anyone can help?

**Comment by prashishh** [comment]
Tagging Pratik (@jedi-knight) who works at Kathmandu Living Labs to give us more insight.

**Comment by jedi-Knight** [comment]
Hi there, exciting to see the project. The site looks amazing!
Regarding the issue:
You can download the OSM data in shp format from this site: http://download.geofabrik.de/asia/nepal.html They're updated daily.
Then, using QGIS, you can extract the city/municipality and vdc boundaries by querying for the attributes _boundary=administrative_  and _admin_level=8_
These boundaries haven't been fully mapped on OSM for all districts though.
You can find the full vdc dataset on other websites, such as here: http://geonode.wfp.org/layers/geonode%3Akhm_pop_adm4population_gov
I think there's one at the HDX site as well: https://data.humdata.org/ but that'll need some thorough search.
But these datasets, although complete, are probably outdated since VDC boundaries change frequently; and these generally lack clearly stated usage terms.
Contacting ICIMOD might also be a good idea since they may have a complete (and probably updated) dataset in the regional database system: http://rds.icimod.org/
ICIMOD has also hosted the admin boundaries on this site: https://www.arcgis.com/home/item.html?id=8ac0e0cf08044731a9309db634c7d894
with the username _admin_nepaleq_ you can try contacting the user of the account as well.
Also, Department of Survey may be able to provide the dataset via their procedure described here: http://ngiip.gov.np/dynamic/resorcDwn
Tagging @nirabpudasaini he might have more info.
