### ISSUE TITLE
Comment from a user  -- regarding presentation of info

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#81]
For the Disabled category, it would make more sense to show % of people disabled in the district, and use that as the basis of comparison.
E.g. saying a district has 10,000 disabled, which is less than 10% of Nepal's 500,000 disabled, isn't that meaningful.
But instead, we could say 1.6% of people in this district are disabled, compared to 2.0% nationally.
And when the percentage is low, it may be more impactful to say "1 in 60 people is disabled"
The ability to compare 2 districts is nice, good layout.
But the site doesn't actually compare them numerically for you. You have to eyeball it.
You could have a feature where for each category, 1 of the 2 districts "wins" by having a higher value for the statistic, and is highlighted. Instead of "about 90 percent of the rate in Nepal," why not "about 10 percent lower..."?

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Here are two screenshots that display a percentage for disability rather than a population count. The first is just one district. The second is a comparison across two districts. This is a straightforward change. A change for "1 in 60" would require a little more work.

As far as the "about 90 percent of the rate in Nepal" language goes, those sorts of descriptive comparison texts are built into Wazimap. If we wanted something different, we would need to explore if and how to make that change.

Lalitpur
![percent-disabled](https://cloud.githubusercontent.com/assets/3824492/19620571/0592e106-9846-11e6-9d0a-c0549e99f588.png)

Humla compared to Jhapa
![disability-comparison](https://cloud.githubusercontent.com/assets/3824492/19620575/168ee1da-9846-11e6-9f90-26e2cebe1029.png)

**Comment by ravinepal** [comment]
@cliftonmcintosh thanks for making the changes. I think it's good for now! We can def explore more in the future!
