### ISSUE TITLE
Upload and integrate VDC level data

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#86]
I just shared VDC shape file with @cliftonmcintosh today. He is working to convert them into geojson files. We are looking for help to match up VDC names with the VDC names that are in the census-data files.

**Comment by cliftonmcintosh** [comment]
Preliminary data is in [this repository](https://github.com/Code4Nepal/geo). Specific VDCs will need to be matched to VDCs that are in the [census-data project](https://github.com/Code4Nepal/census-data). For this to work with the Wazimap framework, each VDC should have a unique code assigned to it.

**Comment by cliftonmcintosh** [comment]
Here are some things that will need to be done to display VDC data:

* Assign a code of 10 characters or less to every VDC. This code must be unique at the VDC level. (Uniqueness per-district is not sufficient.)
* Create a new `vdc.geojson` file in which each VDC has a properties element that matches the structured described in [here](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/README.md). This will likely require a script to transform the data. Scripts for data transformation can be committed to the maptools project. There is a [geo directory](https://github.com/Code4Nepal/maptools/tree/master/geo) for scripts to manipulate geographic data. The new `vdc.geojson` file should be committed to the [geo directory](https://github.com/Code4Nepal/nepalmap_app/tree/dev/wazimap_np/static/geo) in NepalMap.
* Create data that can be imported into the geography database in the structure that can be found [here](https://github.com/Code4Nepal/nepalmap_app/blob/dev/sql/geography.sql#L72). The data should correspond to the properties for each VDC in the geojson file. The data should identify each VDC's parent, in this case a district. Data for import into the database should match the comma-separated structure that is used in the [`geography.sql`](https://github.com/Code4Nepal/nepalmap_app/blob/dev/sql/geography.sql) file. VDC entries can be added to that file for import to the database.
* In order to map data to the VDCs, we need to figure out how to connect the VDC names in the [`vdc.geojson`](https://github.com/Code4Nepal/geo/blob/master/vdc.geojson) file with the VDC names in the [census-data](https://github.com/Code4Nepal/census-data/tree/master/districts) files.
